version: "3.9"
services:
  mysql:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.mysql/data:/var/lib/mysql
